# This file can be used to customize the files managed by PDK.
#
# See https://github.com/puppetlabs/pdk-templates/blob/main/README.md
# for more information.
#
# See https://github.com/puppetlabs/pdk-templates/blob/main/config_defaults.yml
# for the default values.
---
.github/workflows/auto_release.yml:
  unmanaged: false
.github/workflows/ci.yml:
  unmanaged: false
.github/workflows/nightly.yml:
  unmanaged: true
.github/workflows/release_prep.yml:
  unmanaged: false
.github/workflows/release.yml:
  unmanaged: false

.travis.yml:
  delete: true
